### PR TITLE
SetDoNotCacheHeaders in DefaultAntiforgery overrides a more defined cache policy

### PR DESCRIPTION
**Pull request by andyedinborough**
We require revalidation for requests on our site (`Cache-Control: no-cache, no-store, must-revalidate`), but we found that no matter how we set the cache policy it was overridden with a simple "no-cache".

I have attempted a fix.

### CODE REVIEW

**Comment by andyedinborough** [comment]
I'm not sure how the test that's failing wasn't failing before.  The code that logs the warning message will log if either the `Cache-Control` or `Pragma` headers were missing, while the test asserts that the message is not logged if just one of those is present.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2419

**Comment by aspnet-hello** [comment]
Sorry I was a bad bot. Re-opening this PR.

**Comment by Eilon** [comment]
@mkArtakMSFT  - any further action planned on this PR?

**Comment by andyedinborough** [comment]
Because there's been no action on this, I worked around the issue by replacing the default implementation:

```
using Microsoft.AspNetCore.Antiforgery.Internal;
using Microsoft.AspNetCore.Http;
using Microsoft.Net.Http.Headers;

public class Antiforgery : DefaultAntiforgery
{
	public Antiforgery(
		Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Antiforgery.AntiforgeryOptions> antiforgeryOptionsAccessor,
		IAntiforgeryTokenGenerator tokenGenerator,
		IAntiforgeryTokenSerializer tokenSerializer,
		IAntiforgeryTokenStore tokenStore,
		Microsoft.Extensions.Logging.ILoggerFactory loggerFactory)
		: base(antiforgeryOptionsAccessor, tokenGenerator, tokenSerializer, tokenStore, loggerFactory)
	{
	}

	protected override void SetDoNotCacheHeaders(HttpContext httpContext)
	{
		CacheControlHeaderValue.TryParse(httpContext.Response.Headers[HeaderNames.CacheControl][0], out CacheControlHeaderValue cacheControlHeader);
		if (cacheControlHeader == null)
		{
			cacheControlHeader = new CacheControlHeaderValue();
		}

		cacheControlHeader.NoCache = true;
		cacheControlHeader.NoStore = true;
		cacheControlHeader.MustRevalidate = true;
		httpContext.Response.Headers[HeaderNames.CacheControl] = cacheControlHeader.ToString();
		httpContext.Response.Headers[HeaderNames.Pragma] = "no-cache";
	}
}
```

Then in `ConfigureServices(...)`: 
```
    services.AddSingleton<Microsoft.AspNetCore.Antiforgery.IAntiforgery, Antiforgery>();
```

**Comment by natemcmaster** [comment]
I'm closing this PR because this repo is being archived in favor of https://github.com/aspnet/AspNetCore. If this is still something you would like to contribute, please reopen a PR on the new repo.

**Pull request closed without merging**
